-- Supprimer la table CHERCHEUR si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHERCHEUR CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Créer la table CHERCHEUR
CREATE TABLE CHERCHEUR (
  id_chercheur   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom            VARCHAR2(50) NOT NULL,
  prenom         VARCHAR2(50) NOT NULL,
  specialite     VARCHAR2(30) NOT NULL CHECK (specialite IN ('Biotech','IA','Physique','Chimie','Mathématiques','Autre')),
  date_embauche  DATE
);

-- Supprimer la table PROJET si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PROJET CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN 
      RAISE;
    END IF;
END;
/
-- Créer la table PROJET
CREATE TABLE PROJET (
  id_projet          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  titre              VARCHAR2(200),
  domaine            VARCHAR2(100) NOT NULL,
  budget             NUMBER,
  date_debut         DATE,
  date_fin           DATE,
  id_chercheur_resp  NUMBER,
  
  CONSTRAINT pk_projet PRIMARY KEY (id_projet),
  CONSTRAINT ck_budget CHECK (budget > 0),
  CONSTRAINT ck_dates CHECK (date_fin >= date_debut),
  CONSTRAINT fk_projet_chercheur FOREIGN KEY (id_chercheur_resp)
    REFERENCES CHERCHEUR(id_chercheur)
);

-- Supprimer la table EQUIPEMENT si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EQUIPEMENT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Création de la table EQUIPEMENT
CREATE TABLE EQUIPEMENT (
  id_equipement    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom              VARCHAR2(100),
  categorie        VARCHAR2(50) NOT NULL,
  date_acquisition DATE,
  etat             VARCHAR2(30) CHECK (etat IN ('Disponible', 'En maintenance', 'Hors service'))
);


-- Supprimer la table AFFECTATION_EQUIP si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AFFECTATION_EQUIP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Création de la table AFFECTATION_EQUIP
CREATE TABLE AFFECTATION_EQUIP (
      id_affect         NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_projet         NUMBER,
      id_equipement     NUMBER,
      date_affectation  DATE,
      duree_jours       NUMBER CHECK (duree_jours > 0),

      CONSTRAINT pk_affect PRIMARY KEY (id_affect),
      CONSTRAINT fk_affect_projet FOREIGN KEY (id_projet)
          REFERENCES PROJET(id_projet),
      CONSTRAINT fk_affect_equipement FOREIGN KEY (id_equipement)
          REFERENCES EQUIPEMENT(id_equipement)
);

-- Supprimer la table EXPERIENCE si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Création de la table EXPERIENCE
CREATE TABLE EXPERIENCE (
      id_exp            NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_projet         NUMBER,
      titre_exp         VARCHAR2(100),
      date_realisation  DATE,
      resultat          VARCHAR2(100),
      statut            VARCHAR2(20)
        CHECK (statut IN ('En cours', 'Terminée', 'Annulée')),

      CONSTRAINT pk_experience PRIMARY KEY (id_exp),
      CONSTRAINT fk_exp_projet FOREIGN KEY (id_projet)
          REFERENCES PROJET(id_projet)
);

-- Supprimer la table ECHANTILLON si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ECHANTILLON CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Création de la table ECHANTILLON
CREATE TABLE ECHANTILLON (
      id_echantillon    NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_exp            NUMBER,
      type_echantillon  VARCHAR2(100) NOT NULL,
      date_prelevement  DATE,
      mesure            NUMBER CHECK (mesure >= 0),

      CONSTRAINT pk_echantillon PRIMARY KEY (id_echantillon),
      CONSTRAINT fk_echantillon_exp FOREIGN KEY (id_exp)
          REFERENCES EXPERIENCE(id_exp)
);

-- Supprimer la table LOG_OPERATION si elle existe
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_OPERATION CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Création de la table LOG_OPERATION
CREATE TABLE LOG_OPERATION (
      id_log          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      table_concernee VARCHAR2(100),
      operation       VARCHAR2(10)
        CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
      utilisateur     VARCHAR2(50),
      date_op         DATE DEFAULT SYSDATE,
      description     VARCHAR2(500)
);

/*Creation des utilisateurs

CREATE USER ADMIN_LAB IDENTIFIED BY admin123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;
  
CREATE USER GEST_LAB IDENTIFIED BY gest123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

CREATE USER LECT_LAB IDENTIFIED BY lect123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

  Accès des utilisateurs
GRANT CREATE SESSION TO ADMIN_LAB;
GRANT CREATE SESSION TO GEST_LAB;
GRANT CREATE SESSION TO LECT_LAB;

Creation du role ROLE_LAB_RESEARCH
CREATE ROLE ROLE_LAB_RESEARCH;
GRANT SELECT ANY TABLE TO ROLE_LAB_RESEARCH;

Privilèges
GRANT CREATE SESSION, RESOURCE, UNLIMITED TABLESPACE TO ADMIN_LAB;
GRANT ROLE_LAB_RESEARCH TO GEST_LAB;
GRANT ROLE_LAB_RESEARCH TO LECT_LAB;
GRANT INSERT ANY TABLE TO GEST_LAB;
GRANT EXECUTE ANY PROCEDURE TO GEST_LAB;
*/
