-- Création des utilisateurs
CREATE USER ADMIN_LAB IDENTIFIED BY admin_123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

CREATE USER GEST_LAB IDENTIFIED BY gest_123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

CREATE USER LECT_LAB IDENTIFIED BY lect_123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

-- Autorisation de connexion
GRANT CREATE SESSION TO ADMIN_LAB, GEST_LAB, LECT_LAB;

-- Création du rôle commun
CREATE ROLE ROLE_LAB_RESEARCH;

-- Privilèges du schéma principal
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE TRIGGER,
      UNLIMITED TABLESPACE TO ADMIN_LAB;


-- Gestion des exceptions d’exécution de la table CHERCHEUR
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHERCHEUR CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table CHERCHEUR
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CHERCHEUR (
      id_chercheur    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nom             VARCHAR2(50)  NOT NULL,
      prenom          VARCHAR2(50)  NOT NULL,
      specialite      VARCHAR2(30)  NOT NULL
        CHECK (specialite IN ("Biotech", "IA", "Physique", "Chimie", "Mathématiques", "Autre")),
      date_embauche   DATE
        CONSTRAINT chk_date_embauche CHECK (date_embauche <= SYSDATE)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de CHERCHEUR : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table PROJET
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PROJET CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table PROJET
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE PROJET (
      id_projet          NUMBER GENERATED BY DEFAULT AS IDENTITY,
      titre              VARCHAR2(200),
      domaine            VARCHAR2(100) NOT NULL,
      budget             NUMBER CHECK (budget > 0),
      date_debut         DATE,
      date_fin           DATE CHECK (date_fin >= date_debut),
      id_chercheur_resp  NUMBER,
      
      CONSTRAINT pk_projet PRIMARY KEY (id_projet),
      CONSTRAINT fk_projet_chercheur FOREIGN KEY (id_chercheur_resp)
        REFERENCES CHERCHEUR(id_chercheur)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de PROJET : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table EQUIPEMENT
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EQUIPEMENT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table EQUIPEMENT
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE EQUIPEMENT (
      id_equipement      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nom                VARCHAR2(100),
      categorie          VARCHAR2(50) NOT NULL,
      date_acquisition   DATE CHECK (date_acquisition <= SYSDATE),
      etat               VARCHAR2(30)
        CHECK (etat IN ("Disponible", "En maintenance", "Hors service")),
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de EQUIPEMENT : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table AFFECTATION_EQUIP
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AFFECTATION_EQUIP CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table AFFECTATION_EQUIP
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AFFECTATION_EQUIP (
      id_affect         NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_projet         NUMBER,
      id_equipement     NUMBER,
      date_affectation  DATE,
      duree_jours       NUMBER CHECK (duree_jours > 0),

      CONSTRAINT pk_affect PRIMARY KEY (id_affect),
      CONSTRAINT fk_affect_projet FOREIGN KEY (id_projet)
          REFERENCES PROJET(id_projet),
      CONSTRAINT fk_affect_equipement FOREIGN KEY (id_equipement)
          REFERENCES EQUIPEMENT(id_equipement)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de AFFECTATION_EQUIP : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table EXPERIENCE
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table EXPERIENCE
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE EXPERIENCE (
      id_exp            NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_projet         NUMBER,
      titre_exp         VARCHAR2(100),
      date_realisation  DATE,
      resultat          VARCHAR2(100),
      statut            VARCHAR2(20)
        CHECK (statut IN (''En cours'', ''Terminée'', ''Annulée'')),

      CONSTRAINT pk_experience PRIMARY KEY (id_exp),
      CONSTRAINT fk_exp_projet FOREIGN KEY (id_projet)
          REFERENCES PROJET(id_projet)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de EXPERIENCE : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table EXPERIENCE
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ECHANTILLON CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table ECHANTILLON
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE ECHANTILLON (
      id_echantillon    NUMBER GENERATED BY DEFAULT AS IDENTITY,
      id_exp            NUMBER,
      type_echantillon  VARCHAR2(10) NOT NULL,
      date_prelevement  DATE,
      mesure            NUMBER CHECK (mesure >= 0),

      CONSTRAINT pk_echantillon PRIMARY KEY (id_echantillon),
      CONSTRAINT fk_echantillon_exp FOREIGN KEY (id_exp)
          REFERENCES EXPERIENCE(id_exp)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de ECHANTILLON : ' || SQLERRM);
END;
/

-- Gestion des exceptions d’exécution de la table LOG_OPERATION
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_OPERATION CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
-- Table LOG_OPERATION
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE LOG_OPERATION (
      id_log          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      table_concernee VARCHAR2(100),
      operation       VARCHAR2(10)
        CHECK (operation IN (''INSERT'', ''UPDATE'', ''DELETE'')),
      utilisateur     VARCHAR2(50),
      date_op         DATE DEFAULT SYSDATE,
      description     VARCHAR2(500),
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de la création de LOG_OPERATION : ' || SQLERRM);
END;
/
